//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USSS.UsssProcessImplService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.cm.atc/", ConfigurationName="UsssProcessImplService.UsssProcess")]
    public interface UsssProcess {
        
        // CODEGEN: Parameter 'usss' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="usss")]
        USSS.UsssProcessImplService.getUsssResponse getUsss(USSS.UsssProcessImplService.getUsss request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<USSS.UsssProcessImplService.getUsssResponse> getUsssAsync(USSS.UsssProcessImplService.getUsss request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cm.atc/")]
    public partial class usss : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long camp_idField;
        
        private long subgroup_idField;
        
        private string soc_codeField;
        
        private long soc_typeField;
        
        private int score_valueField;
        
        private string treatment_descField;
        
        private string camp_nameField;
        
        private string camp_descField;
        
        private decimal feeField;
        
        private bool feeFieldSpecified;
        
        private long fee_periodField;
        
        private bool fee_periodFieldSpecified;
        
        private decimal priceField;
        
        private bool priceFieldSpecified;
        
        private string currencyField;
        
        private string fttb_ui_id_listField;
        
        private bool new_offer_indField;
        
        private bool new_offer_indFieldSpecified;
        
        private long news_idField;
        
        private bool news_idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long camp_id {
            get {
                return this.camp_idField;
            }
            set {
                this.camp_idField = value;
                this.RaisePropertyChanged("camp_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long subgroup_id {
            get {
                return this.subgroup_idField;
            }
            set {
                this.subgroup_idField = value;
                this.RaisePropertyChanged("subgroup_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string soc_code {
            get {
                return this.soc_codeField;
            }
            set {
                this.soc_codeField = value;
                this.RaisePropertyChanged("soc_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long soc_type {
            get {
                return this.soc_typeField;
            }
            set {
                this.soc_typeField = value;
                this.RaisePropertyChanged("soc_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int score_value {
            get {
                return this.score_valueField;
            }
            set {
                this.score_valueField = value;
                this.RaisePropertyChanged("score_value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string treatment_desc {
            get {
                return this.treatment_descField;
            }
            set {
                this.treatment_descField = value;
                this.RaisePropertyChanged("treatment_desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string camp_name {
            get {
                return this.camp_nameField;
            }
            set {
                this.camp_nameField = value;
                this.RaisePropertyChanged("camp_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string camp_desc {
            get {
                return this.camp_descField;
            }
            set {
                this.camp_descField = value;
                this.RaisePropertyChanged("camp_desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
                this.RaisePropertyChanged("fee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool feeSpecified {
            get {
                return this.feeFieldSpecified;
            }
            set {
                this.feeFieldSpecified = value;
                this.RaisePropertyChanged("feeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public long fee_period {
            get {
                return this.fee_periodField;
            }
            set {
                this.fee_periodField = value;
                this.RaisePropertyChanged("fee_period");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fee_periodSpecified {
            get {
                return this.fee_periodFieldSpecified;
            }
            set {
                this.fee_periodFieldSpecified = value;
                this.RaisePropertyChanged("fee_periodSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
                this.RaisePropertyChanged("priceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string fttb_ui_id_list {
            get {
                return this.fttb_ui_id_listField;
            }
            set {
                this.fttb_ui_id_listField = value;
                this.RaisePropertyChanged("fttb_ui_id_list");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public bool new_offer_ind {
            get {
                return this.new_offer_indField;
            }
            set {
                this.new_offer_indField = value;
                this.RaisePropertyChanged("new_offer_ind");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool new_offer_indSpecified {
            get {
                return this.new_offer_indFieldSpecified;
            }
            set {
                this.new_offer_indFieldSpecified = value;
                this.RaisePropertyChanged("new_offer_indSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public long news_id {
            get {
                return this.news_idField;
            }
            set {
                this.news_idField = value;
                this.RaisePropertyChanged("news_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool news_idSpecified {
            get {
                return this.news_idFieldSpecified;
            }
            set {
                this.news_idFieldSpecified = value;
                this.RaisePropertyChanged("news_idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsss", WrapperNamespace="http://service.cm.atc/", IsWrapped=true)]
    public partial class getUsss {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ctn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long channel_type;
        
        public getUsss() {
        }
        
        public getUsss(string ctn, long channel_type) {
            this.ctn = ctn;
            this.channel_type = channel_type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsssResponse", WrapperNamespace="http://service.cm.atc/", IsWrapped=true)]
    public partial class getUsssResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("usss")]
        public USSS.UsssProcessImplService.usss[] usss;
        
        public getUsssResponse() {
        }
        
        public getUsssResponse(USSS.UsssProcessImplService.usss[] usss) {
            this.usss = usss;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsssProcessChannel : USSS.UsssProcessImplService.UsssProcess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsssProcessClient : System.ServiceModel.ClientBase<USSS.UsssProcessImplService.UsssProcess>, USSS.UsssProcessImplService.UsssProcess {
        
        public UsssProcessClient() {
        }
        
        public UsssProcessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsssProcessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsssProcessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsssProcessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        USSS.UsssProcessImplService.getUsssResponse USSS.UsssProcessImplService.UsssProcess.getUsss(USSS.UsssProcessImplService.getUsss request) {
            return base.Channel.getUsss(request);
        }
        
        public USSS.UsssProcessImplService.usss[] getUsss(string ctn, long channel_type) {
            USSS.UsssProcessImplService.getUsss inValue = new USSS.UsssProcessImplService.getUsss();
            inValue.ctn = ctn;
            inValue.channel_type = channel_type;
            USSS.UsssProcessImplService.getUsssResponse retVal = ((USSS.UsssProcessImplService.UsssProcess)(this)).getUsss(inValue);
            return retVal.usss;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<USSS.UsssProcessImplService.getUsssResponse> USSS.UsssProcessImplService.UsssProcess.getUsssAsync(USSS.UsssProcessImplService.getUsss request) {
            return base.Channel.getUsssAsync(request);
        }
        
        public System.Threading.Tasks.Task<USSS.UsssProcessImplService.getUsssResponse> getUsssAsync(string ctn, long channel_type) {
            USSS.UsssProcessImplService.getUsss inValue = new USSS.UsssProcessImplService.getUsss();
            inValue.ctn = ctn;
            inValue.channel_type = channel_type;
            return ((USSS.UsssProcessImplService.UsssProcess)(this)).getUsssAsync(inValue);
        }
    }
}
