//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USSS.UssProcess3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.cm.atc/", ConfigurationName="UssProcess3.UsssProcess3")]
    public interface UsssProcess3 {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        USSS.UssProcess3.getHistoryResponse getHistory(USSS.UssProcess3.getHistory request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<USSS.UssProcess3.getHistoryResponse> getHistoryAsync(USSS.UssProcess3.getHistory request);
        
        // CODEGEN: Parameter 'USSS' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="USSS")]
        USSS.UssProcess3.getUsssResponse getUsss(USSS.UssProcess3.getUsss request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<USSS.UssProcess3.getUsssResponse> getUsssAsync(USSS.UssProcess3.getUsss request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cm.atc/")]
    public partial class campaignHistory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long camp_idField;
        
        private long subgroup_idField;
        
        private long directionField;
        
        private long categoryField;
        
        private System.DateTime date_inform_main_fromField;
        
        private System.DateTime date_inform_main_toField;
        
        private string camp_nameField;
        
        private string camp_descField;
        
        private string infocenter_linkField;
        
        private long channel_typeField;
        
        private long responseField;
        
        private System.DateTime response_dateField;
        
        private bool response_dateFieldSpecified;
        
        private string employee_numberField;
        
        private System.DateTime date_offeredField;
        
        private bool date_offeredFieldSpecified;
        
        private long outbound_responseField;
        
        private bool outbound_responseFieldSpecified;
        
        private long offer_statusField;
        
        private bool offer_statusFieldSpecified;
        
        private string soc_codeField;
        
        private long soc_typeField;
        
        private bool soc_typeFieldSpecified;
        
        private long news_idField;
        
        private bool news_idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long camp_id {
            get {
                return this.camp_idField;
            }
            set {
                this.camp_idField = value;
                this.RaisePropertyChanged("camp_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long subgroup_id {
            get {
                return this.subgroup_idField;
            }
            set {
                this.subgroup_idField = value;
                this.RaisePropertyChanged("subgroup_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("direction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime date_inform_main_from {
            get {
                return this.date_inform_main_fromField;
            }
            set {
                this.date_inform_main_fromField = value;
                this.RaisePropertyChanged("date_inform_main_from");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime date_inform_main_to {
            get {
                return this.date_inform_main_toField;
            }
            set {
                this.date_inform_main_toField = value;
                this.RaisePropertyChanged("date_inform_main_to");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string camp_name {
            get {
                return this.camp_nameField;
            }
            set {
                this.camp_nameField = value;
                this.RaisePropertyChanged("camp_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string camp_desc {
            get {
                return this.camp_descField;
            }
            set {
                this.camp_descField = value;
                this.RaisePropertyChanged("camp_desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string infocenter_link {
            get {
                return this.infocenter_linkField;
            }
            set {
                this.infocenter_linkField = value;
                this.RaisePropertyChanged("infocenter_link");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public long channel_type {
            get {
                return this.channel_typeField;
            }
            set {
                this.channel_typeField = value;
                this.RaisePropertyChanged("channel_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public long response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public System.DateTime response_date {
            get {
                return this.response_dateField;
            }
            set {
                this.response_dateField = value;
                this.RaisePropertyChanged("response_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool response_dateSpecified {
            get {
                return this.response_dateFieldSpecified;
            }
            set {
                this.response_dateFieldSpecified = value;
                this.RaisePropertyChanged("response_dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string employee_number {
            get {
                return this.employee_numberField;
            }
            set {
                this.employee_numberField = value;
                this.RaisePropertyChanged("employee_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public System.DateTime date_offered {
            get {
                return this.date_offeredField;
            }
            set {
                this.date_offeredField = value;
                this.RaisePropertyChanged("date_offered");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool date_offeredSpecified {
            get {
                return this.date_offeredFieldSpecified;
            }
            set {
                this.date_offeredFieldSpecified = value;
                this.RaisePropertyChanged("date_offeredSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public long outbound_response {
            get {
                return this.outbound_responseField;
            }
            set {
                this.outbound_responseField = value;
                this.RaisePropertyChanged("outbound_response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool outbound_responseSpecified {
            get {
                return this.outbound_responseFieldSpecified;
            }
            set {
                this.outbound_responseFieldSpecified = value;
                this.RaisePropertyChanged("outbound_responseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public long offer_status {
            get {
                return this.offer_statusField;
            }
            set {
                this.offer_statusField = value;
                this.RaisePropertyChanged("offer_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool offer_statusSpecified {
            get {
                return this.offer_statusFieldSpecified;
            }
            set {
                this.offer_statusFieldSpecified = value;
                this.RaisePropertyChanged("offer_statusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string soc_code {
            get {
                return this.soc_codeField;
            }
            set {
                this.soc_codeField = value;
                this.RaisePropertyChanged("soc_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public long soc_type {
            get {
                return this.soc_typeField;
            }
            set {
                this.soc_typeField = value;
                this.RaisePropertyChanged("soc_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool soc_typeSpecified {
            get {
                return this.soc_typeFieldSpecified;
            }
            set {
                this.soc_typeFieldSpecified = value;
                this.RaisePropertyChanged("soc_typeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public long news_id {
            get {
                return this.news_idField;
            }
            set {
                this.news_idField = value;
                this.RaisePropertyChanged("news_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool news_idSpecified {
            get {
                return this.news_idFieldSpecified;
            }
            set {
                this.news_idFieldSpecified = value;
                this.RaisePropertyChanged("news_idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cm.atc/")]
    public partial class usss : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long camp_idField;
        
        private long subgroup_idField;
        
        private string soc_codeField;
        
        private long soc_typeField;
        
        private int score_valueField;
        
        private string treatment_descField;
        
        private string camp_nameField;
        
        private string camp_descField;
        
        private decimal feeField;
        
        private bool feeFieldSpecified;
        
        private long fee_periodField;
        
        private bool fee_periodFieldSpecified;
        
        private decimal priceField;
        
        private bool priceFieldSpecified;
        
        private string currencyField;
        
        private string fttb_ui_id_listField;
        
        private bool new_offer_indField;
        
        private bool new_offer_indFieldSpecified;
        
        private long news_idField;
        
        private bool news_idFieldSpecified;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long camp_id {
            get {
                return this.camp_idField;
            }
            set {
                this.camp_idField = value;
                this.RaisePropertyChanged("camp_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long subgroup_id {
            get {
                return this.subgroup_idField;
            }
            set {
                this.subgroup_idField = value;
                this.RaisePropertyChanged("subgroup_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string soc_code {
            get {
                return this.soc_codeField;
            }
            set {
                this.soc_codeField = value;
                this.RaisePropertyChanged("soc_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long soc_type {
            get {
                return this.soc_typeField;
            }
            set {
                this.soc_typeField = value;
                this.RaisePropertyChanged("soc_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int score_value {
            get {
                return this.score_valueField;
            }
            set {
                this.score_valueField = value;
                this.RaisePropertyChanged("score_value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string treatment_desc {
            get {
                return this.treatment_descField;
            }
            set {
                this.treatment_descField = value;
                this.RaisePropertyChanged("treatment_desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string camp_name {
            get {
                return this.camp_nameField;
            }
            set {
                this.camp_nameField = value;
                this.RaisePropertyChanged("camp_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string camp_desc {
            get {
                return this.camp_descField;
            }
            set {
                this.camp_descField = value;
                this.RaisePropertyChanged("camp_desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
                this.RaisePropertyChanged("fee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool feeSpecified {
            get {
                return this.feeFieldSpecified;
            }
            set {
                this.feeFieldSpecified = value;
                this.RaisePropertyChanged("feeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public long fee_period {
            get {
                return this.fee_periodField;
            }
            set {
                this.fee_periodField = value;
                this.RaisePropertyChanged("fee_period");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fee_periodSpecified {
            get {
                return this.fee_periodFieldSpecified;
            }
            set {
                this.fee_periodFieldSpecified = value;
                this.RaisePropertyChanged("fee_periodSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
                this.RaisePropertyChanged("priceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string fttb_ui_id_list {
            get {
                return this.fttb_ui_id_listField;
            }
            set {
                this.fttb_ui_id_listField = value;
                this.RaisePropertyChanged("fttb_ui_id_list");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public bool new_offer_ind {
            get {
                return this.new_offer_indField;
            }
            set {
                this.new_offer_indField = value;
                this.RaisePropertyChanged("new_offer_ind");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool new_offer_indSpecified {
            get {
                return this.new_offer_indFieldSpecified;
            }
            set {
                this.new_offer_indFieldSpecified = value;
                this.RaisePropertyChanged("new_offer_indSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public long news_id {
            get {
                return this.news_idField;
            }
            set {
                this.news_idField = value;
                this.RaisePropertyChanged("news_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool news_idSpecified {
            get {
                return this.news_idFieldSpecified;
            }
            set {
                this.news_idFieldSpecified = value;
                this.RaisePropertyChanged("news_idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cm.atc/")]
    public partial class eventParam : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string param_nameField;
        
        private string param_valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string param_name {
            get {
                return this.param_nameField;
            }
            set {
                this.param_nameField = value;
                this.RaisePropertyChanged("param_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string param_value {
            get {
                return this.param_valueField;
            }
            set {
                this.param_valueField = value;
                this.RaisePropertyChanged("param_value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cm.atc/")]
    public partial class iptvService : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long base_idField;
        
        private decimal priceField;
        
        private bool priceFieldSpecified;
        
        private bool in_bundleField;
        
        private bool in_bundleFieldSpecified;
        
        private long[] packet_listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long base_id {
            get {
                return this.base_idField;
            }
            set {
                this.base_idField = value;
                this.RaisePropertyChanged("base_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
                this.RaisePropertyChanged("priceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool in_bundle {
            get {
                return this.in_bundleField;
            }
            set {
                this.in_bundleField = value;
                this.RaisePropertyChanged("in_bundle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool in_bundleSpecified {
            get {
                return this.in_bundleFieldSpecified;
            }
            set {
                this.in_bundleFieldSpecified = value;
                this.RaisePropertyChanged("in_bundleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("packet_id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public long[] packet_list {
            get {
                return this.packet_listField;
            }
            set {
                this.packet_listField = value;
                this.RaisePropertyChanged("packet_list");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.cm.atc/")]
    public partial class fttbService : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string typeField;
        
        private decimal priceField;
        
        private bool priceFieldSpecified;
        
        private bool in_bundleField;
        
        private bool in_bundleFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
                this.RaisePropertyChanged("priceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool in_bundle {
            get {
                return this.in_bundleField;
            }
            set {
                this.in_bundleField = value;
                this.RaisePropertyChanged("in_bundle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool in_bundleSpecified {
            get {
                return this.in_bundleFieldSpecified;
            }
            set {
                this.in_bundleFieldSpecified = value;
                this.RaisePropertyChanged("in_bundleSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHistory", WrapperNamespace="http://service.cm.atc/", IsWrapped=true)]
    public partial class getHistory {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ctn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long channel_type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long response;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long direction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long category;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime start_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime end_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long soc_type;
        
        public getHistory() {
        }
        
        public getHistory(string ctn, long channel_type, long response, long direction, long category, System.DateTime start_date, System.DateTime end_date, long soc_type) {
            this.ctn = ctn;
            this.channel_type = channel_type;
            this.response = response;
            this.direction = direction;
            this.category = category;
            this.start_date = start_date;
            this.end_date = end_date;
            this.soc_type = soc_type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHistoryResponse", WrapperNamespace="http://service.cm.atc/", IsWrapped=true)]
    public partial class getHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public USSS.UssProcess3.campaignHistory[] @return;
        
        public getHistoryResponse() {
        }
        
        public getHistoryResponse(USSS.UssProcess3.campaignHistory[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsss", WrapperNamespace="http://service.cm.atc/", IsWrapped=true)]
    public partial class getUsss {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ctn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long channel_type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal fttb_balance;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fttb_currency;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fttb_activity_reason_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=5)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("fttb_service", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public USSS.UssProcess3.fttbService[] fttb_service_list;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=6)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("iptv_service", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public USSS.UssProcess3.iptvService[] iptv_service_list;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal fttb_total_service_price;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string master_login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fttb_hide_offer_ind;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long event_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=11)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("event_param", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public USSS.UssProcess3.eventParam[] event_param_list;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool fttb_trust_payment_ind;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool fttb_auto_payment_ind;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fttb_billing_end_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool impersonalization_ind;
        
        public getUsss() {
        }
        
        public getUsss(
                    string ctn, 
                    long channel_type, 
                    decimal fttb_balance, 
                    string fttb_currency, 
                    int fttb_activity_reason_code, 
                    USSS.UssProcess3.fttbService[] fttb_service_list, 
                    USSS.UssProcess3.iptvService[] iptv_service_list, 
                    decimal fttb_total_service_price, 
                    string master_login, 
                    int fttb_hide_offer_ind, 
                    long event_id, 
                    USSS.UssProcess3.eventParam[] event_param_list, 
                    bool fttb_trust_payment_ind, 
                    bool fttb_auto_payment_ind, 
                    System.DateTime fttb_billing_end_date, 
                    bool impersonalization_ind) {
            this.ctn = ctn;
            this.channel_type = channel_type;
            this.fttb_balance = fttb_balance;
            this.fttb_currency = fttb_currency;
            this.fttb_activity_reason_code = fttb_activity_reason_code;
            this.fttb_service_list = fttb_service_list;
            this.iptv_service_list = iptv_service_list;
            this.fttb_total_service_price = fttb_total_service_price;
            this.master_login = master_login;
            this.fttb_hide_offer_ind = fttb_hide_offer_ind;
            this.event_id = event_id;
            this.event_param_list = event_param_list;
            this.fttb_trust_payment_ind = fttb_trust_payment_ind;
            this.fttb_auto_payment_ind = fttb_auto_payment_ind;
            this.fttb_billing_end_date = fttb_billing_end_date;
            this.impersonalization_ind = impersonalization_ind;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsssResponse", WrapperNamespace="http://service.cm.atc/", IsWrapped=true)]
    public partial class getUsssResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.cm.atc/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("USSS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public USSS.UssProcess3.usss[] USSS;
        
        public getUsssResponse() {
        }
        
        public getUsssResponse(USSS.UssProcess3.usss[] USSS) {
            this.USSS = USSS;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsssProcess3Channel : USSS.UssProcess3.UsssProcess3, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsssProcess3Client : System.ServiceModel.ClientBase<USSS.UssProcess3.UsssProcess3>, USSS.UssProcess3.UsssProcess3 {
        
        public UsssProcess3Client() {
        }
        
        public UsssProcess3Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsssProcess3Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsssProcess3Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsssProcess3Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        USSS.UssProcess3.getHistoryResponse USSS.UssProcess3.UsssProcess3.getHistory(USSS.UssProcess3.getHistory request) {
            return base.Channel.getHistory(request);
        }
        
        public USSS.UssProcess3.campaignHistory[] getHistory(string ctn, long channel_type, long response, long direction, long category, System.DateTime start_date, System.DateTime end_date, long soc_type) {
            USSS.UssProcess3.getHistory inValue = new USSS.UssProcess3.getHistory();
            inValue.ctn = ctn;
            inValue.channel_type = channel_type;
            inValue.response = response;
            inValue.direction = direction;
            inValue.category = category;
            inValue.start_date = start_date;
            inValue.end_date = end_date;
            inValue.soc_type = soc_type;
            USSS.UssProcess3.getHistoryResponse retVal = ((USSS.UssProcess3.UsssProcess3)(this)).getHistory(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<USSS.UssProcess3.getHistoryResponse> USSS.UssProcess3.UsssProcess3.getHistoryAsync(USSS.UssProcess3.getHistory request) {
            return base.Channel.getHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<USSS.UssProcess3.getHistoryResponse> getHistoryAsync(string ctn, long channel_type, long response, long direction, long category, System.DateTime start_date, System.DateTime end_date, long soc_type) {
            USSS.UssProcess3.getHistory inValue = new USSS.UssProcess3.getHistory();
            inValue.ctn = ctn;
            inValue.channel_type = channel_type;
            inValue.response = response;
            inValue.direction = direction;
            inValue.category = category;
            inValue.start_date = start_date;
            inValue.end_date = end_date;
            inValue.soc_type = soc_type;
            return ((USSS.UssProcess3.UsssProcess3)(this)).getHistoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        USSS.UssProcess3.getUsssResponse USSS.UssProcess3.UsssProcess3.getUsss(USSS.UssProcess3.getUsss request) {
            return base.Channel.getUsss(request);
        }
        
        public USSS.UssProcess3.usss[] getUsss(
                    string ctn, 
                    long channel_type, 
                    decimal fttb_balance, 
                    string fttb_currency, 
                    int fttb_activity_reason_code, 
                    USSS.UssProcess3.fttbService[] fttb_service_list, 
                    USSS.UssProcess3.iptvService[] iptv_service_list, 
                    decimal fttb_total_service_price, 
                    string master_login, 
                    int fttb_hide_offer_ind, 
                    long event_id, 
                    USSS.UssProcess3.eventParam[] event_param_list, 
                    bool fttb_trust_payment_ind, 
                    bool fttb_auto_payment_ind, 
                    System.DateTime fttb_billing_end_date, 
                    bool impersonalization_ind) {
            USSS.UssProcess3.getUsss inValue = new USSS.UssProcess3.getUsss();
            inValue.ctn = ctn;
            inValue.channel_type = channel_type;
            inValue.fttb_balance = fttb_balance;
            inValue.fttb_currency = fttb_currency;
            inValue.fttb_activity_reason_code = fttb_activity_reason_code;
            inValue.fttb_service_list = fttb_service_list;
            inValue.iptv_service_list = iptv_service_list;
            inValue.fttb_total_service_price = fttb_total_service_price;
            inValue.master_login = master_login;
            inValue.fttb_hide_offer_ind = fttb_hide_offer_ind;
            inValue.event_id = event_id;
            inValue.event_param_list = event_param_list;
            inValue.fttb_trust_payment_ind = fttb_trust_payment_ind;
            inValue.fttb_auto_payment_ind = fttb_auto_payment_ind;
            inValue.fttb_billing_end_date = fttb_billing_end_date;
            inValue.impersonalization_ind = impersonalization_ind;
            USSS.UssProcess3.getUsssResponse retVal = ((USSS.UssProcess3.UsssProcess3)(this)).getUsss(inValue);
            return retVal.USSS;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<USSS.UssProcess3.getUsssResponse> USSS.UssProcess3.UsssProcess3.getUsssAsync(USSS.UssProcess3.getUsss request) {
            return base.Channel.getUsssAsync(request);
        }
        
        public System.Threading.Tasks.Task<USSS.UssProcess3.getUsssResponse> getUsssAsync(
                    string ctn, 
                    long channel_type, 
                    decimal fttb_balance, 
                    string fttb_currency, 
                    int fttb_activity_reason_code, 
                    USSS.UssProcess3.fttbService[] fttb_service_list, 
                    USSS.UssProcess3.iptvService[] iptv_service_list, 
                    decimal fttb_total_service_price, 
                    string master_login, 
                    int fttb_hide_offer_ind, 
                    long event_id, 
                    USSS.UssProcess3.eventParam[] event_param_list, 
                    bool fttb_trust_payment_ind, 
                    bool fttb_auto_payment_ind, 
                    System.DateTime fttb_billing_end_date, 
                    bool impersonalization_ind) {
            USSS.UssProcess3.getUsss inValue = new USSS.UssProcess3.getUsss();
            inValue.ctn = ctn;
            inValue.channel_type = channel_type;
            inValue.fttb_balance = fttb_balance;
            inValue.fttb_currency = fttb_currency;
            inValue.fttb_activity_reason_code = fttb_activity_reason_code;
            inValue.fttb_service_list = fttb_service_list;
            inValue.iptv_service_list = iptv_service_list;
            inValue.fttb_total_service_price = fttb_total_service_price;
            inValue.master_login = master_login;
            inValue.fttb_hide_offer_ind = fttb_hide_offer_ind;
            inValue.event_id = event_id;
            inValue.event_param_list = event_param_list;
            inValue.fttb_trust_payment_ind = fttb_trust_payment_ind;
            inValue.fttb_auto_payment_ind = fttb_auto_payment_ind;
            inValue.fttb_billing_end_date = fttb_billing_end_date;
            inValue.impersonalization_ind = impersonalization_ind;
            return ((USSS.UssProcess3.UsssProcess3)(this)).getUsssAsync(inValue);
        }
    }
}
