//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USSS.AuthSoap {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:uss-wsapi:Auth")]
    public partial class UssWsApiException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        private string errorDescriptionField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorCodeSpecified {
            get {
                return this.errorCodeFieldSpecified;
            }
            set {
                this.errorCodeFieldSpecified = value;
                this.RaisePropertyChanged("errorCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:uss-wsapi:Auth", ConfigurationName="AuthSoap.AuthInterface")]
    public interface AuthInterface {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:uss-wsapi:Auth:AuthInterface:authRequest", ReplyAction="urn:uss-wsapi:Auth:AuthInterface:authResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(USSS.AuthSoap.UssWsApiException), Action="urn:uss-wsapi:Auth:AuthInterface:auth:Fault:UssWsApiException", Name="UssWsApiException", Namespace="urn:uss-wsapi:Types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        USSS.AuthSoap.authResponse auth(USSS.AuthSoap.authRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:uss-wsapi:Auth:AuthInterface:authRequest", ReplyAction="urn:uss-wsapi:Auth:AuthInterface:authResponse")]
        System.Threading.Tasks.Task<USSS.AuthSoap.authResponse> authAsync(USSS.AuthSoap.authRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="auth", WrapperNamespace="urn:uss-wsapi:Auth", IsWrapped=true)]
    public partial class authRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uss-wsapi:Auth", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uss-wsapi:Auth", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public authRequest() {
        }
        
        public authRequest(string login, string password) {
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authResponse", WrapperNamespace="urn:uss-wsapi:Auth", IsWrapped=true)]
    public partial class authResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:uss-wsapi:Auth", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public authResponse() {
        }
        
        public authResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthInterfaceChannel : USSS.AuthSoap.AuthInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthInterfaceClient : System.ServiceModel.ClientBase<USSS.AuthSoap.AuthInterface>, USSS.AuthSoap.AuthInterface {
        
        public AuthInterfaceClient() {
        }
        
        public AuthInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        USSS.AuthSoap.authResponse USSS.AuthSoap.AuthInterface.auth(USSS.AuthSoap.authRequest request) {
            return base.Channel.auth(request);
        }
        
        public string auth(string login, string password) {
            USSS.AuthSoap.authRequest inValue = new USSS.AuthSoap.authRequest();
            inValue.login = login;
            inValue.password = password;
            USSS.AuthSoap.authResponse retVal = ((USSS.AuthSoap.AuthInterface)(this)).auth(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<USSS.AuthSoap.authResponse> USSS.AuthSoap.AuthInterface.authAsync(USSS.AuthSoap.authRequest request) {
            return base.Channel.authAsync(request);
        }
        
        public System.Threading.Tasks.Task<USSS.AuthSoap.authResponse> authAsync(string login, string password) {
            USSS.AuthSoap.authRequest inValue = new USSS.AuthSoap.authRequest();
            inValue.login = login;
            inValue.password = password;
            return ((USSS.AuthSoap.AuthInterface)(this)).authAsync(inValue);
        }
    }
}
